import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = '/bootstrap/4.0.0-beta';


  list = [{
    "id": 1,
    "first_name": "Errol",
    "last_name": "Helder",
    "email": "ehelder0@chronoengine.com",
    "gender": "Male",
    "ip_address": "120.232.95.1",
    "picture": "http://dummyimage.com/199x140.jpg/ff4444/ffffff"
  }, {
    "id": 2,
    "first_name": "Willy",
    "last_name": "Gaffey",
    "email": "wgaffey1@csmonitor.com",
    "gender": "Male",
    "ip_address": "61.50.192.108",
    "picture": "http://dummyimage.com/136x168.bmp/ff4444/ffffff"
  }, {
    "id": 3,
    "first_name": "Stesha",
    "last_name": "Vanshin",
    "email": "svanshin2@infoseek.co.jp",
    "gender": "Female",
    "ip_address": "97.88.112.10",
    "picture": "http://dummyimage.com/145x184.jpg/ff4444/ffffff"
  }, {
    "id": 4,
    "first_name": "Eldon",
    "last_name": "Grundwater",
    "email": "egrundwater3@nbcnews.com",
    "gender": "Male",
    "ip_address": "223.216.102.92",
    "picture": "http://dummyimage.com/228x142.png/dddddd/000000"
  }, {
    "id": 5,
    "first_name": "Sarita",
    "last_name": "Leetham",
    "email": "sleetham4@tripadvisor.com",
    "gender": "Female",
    "ip_address": "53.187.51.38",
    "picture": "http://dummyimage.com/173x188.png/ff4444/ffffff"
  }, {
    "id": 6,
    "first_name": "Warde",
    "last_name": "Dearell",
    "email": "wdearell5@vimeo.com",
    "gender": "Male",
    "ip_address": "193.103.190.73",
    "picture": "http://dummyimage.com/105x124.png/dddddd/000000"
  }, {
    "id": 7,
    "first_name": "Harcourt",
    "last_name": "Teece",
    "email": "hteece6@mit.edu",
    "gender": "Male",
    "ip_address": "104.202.26.8",
    "picture": "http://dummyimage.com/109x227.bmp/5fa2dd/ffffff"
  }, {
    "id": 8,
    "first_name": "Serena",
    "last_name": "Magowan",
    "email": "smagowan7@51.la",
    "gender": "Female",
    "ip_address": "27.202.246.158",
    "picture": "http://dummyimage.com/234x245.jpg/dddddd/000000"
  }, {
    "id": 9,
    "first_name": "Deane",
    "last_name": "Pancost",
    "email": "dpancost8@de.vu",
    "gender": "Male",
    "ip_address": "16.5.162.31",
    "picture": "http://dummyimage.com/126x242.bmp/cc0000/ffffff"
  }, {
    "id": 10,
    "first_name": "Fitz",
    "last_name": "Eisold",
    "email": "feisold9@netscape.com",
    "gender": "Male",
    "ip_address": "222.130.157.176",
    "picture": "http://dummyimage.com/250x169.bmp/ff4444/ffffff"
  }, {
    "id": 11,
    "first_name": "Arda",
    "last_name": "Longshaw",
    "email": "alongshawa@zdnet.com",
    "gender": "Female",
    "ip_address": "126.32.211.74",
    "picture": "http://dummyimage.com/116x102.png/dddddd/000000"
  }, {
    "id": 12,
    "first_name": "Nathaniel",
    "last_name": "Siman",
    "email": "nsimanb@irs.gov",
    "gender": "Male",
    "ip_address": "117.173.188.32",
    "picture": "http://dummyimage.com/103x211.png/dddddd/000000"
  }, {
    "id": 13,
    "first_name": "Chic",
    "last_name": "Millions",
    "email": "cmillionsc@exblog.jp",
    "gender": "Male",
    "ip_address": "229.194.129.66",
    "picture": "http://dummyimage.com/187x189.png/ff4444/ffffff"
  }, {
    "id": 14,
    "first_name": "Baldwin",
    "last_name": "Gisburne",
    "email": "bgisburned@disqus.com",
    "gender": "Male",
    "ip_address": "76.19.35.76",
    "picture": "http://dummyimage.com/230x250.bmp/5fa2dd/ffffff"
  }, {
    "id": 15,
    "first_name": "Elroy",
    "last_name": "Wann",
    "email": "ewanne@devhub.com",
    "gender": "Male",
    "ip_address": "39.1.186.71",
    "picture": "http://dummyimage.com/103x232.png/dddddd/000000"
  }, {
    "id": 16,
    "first_name": "Jill",
    "last_name": "Crudgington",
    "email": "jcrudgingtonf@surveymonkey.com",
    "gender": "Female",
    "ip_address": "35.91.64.169",
    "picture": "http://dummyimage.com/223x225.png/cc0000/ffffff"
  }, {
    "id": 17,
    "first_name": "Cirstoforo",
    "last_name": "Francescotti",
    "email": "cfrancescottig@cargocollective.com",
    "gender": "Male",
    "ip_address": "118.42.226.216",
    "picture": "http://dummyimage.com/126x158.png/5fa2dd/ffffff"
  }, {
    "id": 18,
    "first_name": "Liam",
    "last_name": "McIndoe",
    "email": "lmcindoeh@homestead.com",
    "gender": "Male",
    "ip_address": "93.222.114.57",
    "picture": "http://dummyimage.com/172x221.jpg/cc0000/ffffff"
  }, {
    "id": 19,
    "first_name": "Meggy",
    "last_name": "Fricker",
    "email": "mfrickeri@imageshack.us",
    "gender": "Female",
    "ip_address": "38.33.215.154",
    "picture": "http://dummyimage.com/156x218.png/dddddd/000000"
  }, {
    "id": 20,
    "first_name": "Blondie",
    "last_name": "Worwood",
    "email": "bworwoodj@bloomberg.com",
    "gender": "Female",
    "ip_address": "100.22.107.199",
    "picture": "http://dummyimage.com/125x236.bmp/5fa2dd/ffffff"
  }, {
    "id": 21,
    "first_name": "Antone",
    "last_name": "Pietruszewicz",
    "email": "apietruszewiczk@artisteer.com",
    "gender": "Male",
    "ip_address": "191.249.197.94",
    "picture": "http://dummyimage.com/219x155.jpg/cc0000/ffffff"
  }, {
    "id": 22,
    "first_name": "Joseito",
    "last_name": "Rosoni",
    "email": "jrosonil@yellowpages.com",
    "gender": "Male",
    "ip_address": "28.160.138.142",
    "picture": "http://dummyimage.com/135x181.bmp/5fa2dd/ffffff"
  }, {
    "id": 23,
    "first_name": "Anica",
    "last_name": "Targe",
    "email": "atargem@usa.gov",
    "gender": "Female",
    "ip_address": "5.90.128.127",
    "picture": "http://dummyimage.com/140x209.jpg/cc0000/ffffff"
  }, {
    "id": 24,
    "first_name": "Isacco",
    "last_name": "Goneau",
    "email": "igoneaun@dropbox.com",
    "gender": "Male",
    "ip_address": "27.136.150.221",
    "picture": "http://dummyimage.com/183x151.bmp/ff4444/ffffff"
  }, {
    "id": 25,
    "first_name": "Vin",
    "last_name": "Karlmann",
    "email": "vkarlmanno@ask.com",
    "gender": "Female",
    "ip_address": "131.201.132.20",
    "picture": "http://dummyimage.com/134x132.png/5fa2dd/ffffff"
  }, {
    "id": 26,
    "first_name": "Larina",
    "last_name": "Treves",
    "email": "ltrevesp@cmu.edu",
    "gender": "Female",
    "ip_address": "54.239.114.141",
    "picture": "http://dummyimage.com/230x225.bmp/dddddd/000000"
  }, {
    "id": 27,
    "first_name": "Anastasie",
    "last_name": "Caven",
    "email": "acavenq@virginia.edu",
    "gender": "Female",
    "ip_address": "51.51.202.19",
    "picture": "http://dummyimage.com/234x112.png/cc0000/ffffff"
  }, {
    "id": 28,
    "first_name": "Nanni",
    "last_name": "Cleft",
    "email": "ncleftr@topsy.com",
    "gender": "Female",
    "ip_address": "3.138.237.25",
    "picture": "http://dummyimage.com/131x150.bmp/ff4444/ffffff"
  }, {
    "id": 29,
    "first_name": "Ulrich",
    "last_name": "Martin",
    "email": "umartins@cbsnews.com",
    "gender": "Male",
    "ip_address": "114.240.71.118",
    "picture": "http://dummyimage.com/169x177.jpg/5fa2dd/ffffff"
  }, {
    "id": 30,
    "first_name": "Torey",
    "last_name": "Robrose",
    "email": "trobroset@wp.com",
    "gender": "Male",
    "ip_address": "234.241.182.204",
    "picture": "http://dummyimage.com/114x156.png/cc0000/ffffff"
  }, {
    "id": 31,
    "first_name": "Jada",
    "last_name": "Quested",
    "email": "jquestedu@dedecms.com",
    "gender": "Female",
    "ip_address": "251.106.117.149",
    "picture": "http://dummyimage.com/199x168.jpg/cc0000/ffffff"
  }, {
    "id": 32,
    "first_name": "Ki",
    "last_name": "Drinkall",
    "email": "kdrinkallv@bigcartel.com",
    "gender": "Female",
    "ip_address": "143.37.196.62",
    "picture": "http://dummyimage.com/158x110.bmp/dddddd/000000"
  }, {
    "id": 33,
    "first_name": "Stevie",
    "last_name": "Kloss",
    "email": "sklossw@alibaba.com",
    "gender": "Male",
    "ip_address": "69.135.39.136",
    "picture": "http://dummyimage.com/190x225.bmp/5fa2dd/ffffff"
  }, {
    "id": 34,
    "first_name": "Eddie",
    "last_name": "Scrivin",
    "email": "escrivinx@imageshack.us",
    "gender": "Female",
    "ip_address": "43.208.213.27",
    "picture": "http://dummyimage.com/239x141.bmp/5fa2dd/ffffff"
  }, {
    "id": 35,
    "first_name": "Kaitlynn",
    "last_name": "Deacon",
    "email": "kdeacony@ask.com",
    "gender": "Female",
    "ip_address": "252.104.193.234",
    "picture": "http://dummyimage.com/108x155.bmp/5fa2dd/ffffff"
  }, {
    "id": 36,
    "first_name": "Fara",
    "last_name": "Trenbay",
    "email": "ftrenbayz@imdb.com",
    "gender": "Female",
    "ip_address": "171.110.153.217",
    "picture": "http://dummyimage.com/173x186.jpg/dddddd/000000"
  }, {
    "id": 37,
    "first_name": "Yelena",
    "last_name": "De Cruze",
    "email": "ydecruze10@is.gd",
    "gender": "Female",
    "ip_address": "127.4.234.177",
    "picture": "http://dummyimage.com/134x127.bmp/ff4444/ffffff"
  }, {
    "id": 38,
    "first_name": "Roselin",
    "last_name": "Kaley",
    "email": "rkaley11@gravatar.com",
    "gender": "Female",
    "ip_address": "67.83.114.132",
    "picture": "http://dummyimage.com/122x216.jpg/dddddd/000000"
  }, {
    "id": 39,
    "first_name": "Say",
    "last_name": "Piletic",
    "email": "spiletic12@google.fr",
    "gender": "Male",
    "ip_address": "149.250.100.94",
    "picture": "http://dummyimage.com/226x120.bmp/5fa2dd/ffffff"
  }, {
    "id": 40,
    "first_name": "Christabel",
    "last_name": "Fairham",
    "email": "cfairham13@springer.com",
    "gender": "Female",
    "ip_address": "5.123.229.3",
    "picture": "http://dummyimage.com/114x149.bmp/5fa2dd/ffffff"
  }, {
    "id": 41,
    "first_name": "Justin",
    "last_name": "Brumwell",
    "email": "jbrumwell14@indiatimes.com",
    "gender": "Male",
    "ip_address": "228.26.203.26",
    "picture": "http://dummyimage.com/124x199.jpg/5fa2dd/ffffff"
  }, {
    "id": 42,
    "first_name": "Kenna",
    "last_name": "Fogden",
    "email": "kfogden15@smugmug.com",
    "gender": "Female",
    "ip_address": "2.138.192.196",
    "picture": "http://dummyimage.com/176x207.jpg/ff4444/ffffff"
  }, {
    "id": 43,
    "first_name": "Mil",
    "last_name": "Veld",
    "email": "mveld16@squarespace.com",
    "gender": "Female",
    "ip_address": "97.131.172.103",
    "picture": "http://dummyimage.com/238x235.bmp/ff4444/ffffff"
  }, {
    "id": 44,
    "first_name": "Kial",
    "last_name": "Carluccio",
    "email": "kcarluccio17@bing.com",
    "gender": "Female",
    "ip_address": "168.120.126.118",
    "picture": "http://dummyimage.com/250x246.bmp/cc0000/ffffff"
  }, {
    "id": 45,
    "first_name": "Coleman",
    "last_name": "Urlin",
    "email": "curlin18@google.de",
    "gender": "Male",
    "ip_address": "68.151.152.27",
    "picture": "http://dummyimage.com/210x120.png/dddddd/000000"
  }, {
    "id": 46,
    "first_name": "Francyne",
    "last_name": "Braybrook",
    "email": "fbraybrook19@techcrunch.com",
    "gender": "Female",
    "ip_address": "176.23.161.55",
    "picture": "http://dummyimage.com/217x136.jpg/cc0000/ffffff"
  }, {
    "id": 47,
    "first_name": "Grover",
    "last_name": "Daveran",
    "email": "gdaveran1a@auda.org.au",
    "gender": "Male",
    "ip_address": "27.74.82.164",
    "picture": "http://dummyimage.com/209x142.png/5fa2dd/ffffff"
  }, {
    "id": 48,
    "first_name": "Neila",
    "last_name": "Lyver",
    "email": "nlyver1b@goo.gl",
    "gender": "Female",
    "ip_address": "159.253.127.152",
    "picture": "http://dummyimage.com/104x116.bmp/cc0000/ffffff"
  }, {
    "id": 49,
    "first_name": "Freda",
    "last_name": "Tuma",
    "email": "ftuma1c@un.org",
    "gender": "Female",
    "ip_address": "216.20.145.87",
    "picture": "http://dummyimage.com/175x240.png/5fa2dd/ffffff"
  }, {
    "id": 50,
    "first_name": "Riccardo",
    "last_name": "Grigoryov",
    "email": "rgrigoryov1d@narod.ru",
    "gender": "Male",
    "ip_address": "66.33.213.13",
    "picture": "http://dummyimage.com/145x187.jpg/ff4444/ffffff"
  }]
}